spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: IOTL

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ${JWT_SECRET}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: https://iotl.store/login/oauth2/code/naver #http://iotl:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://iotl.store/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}   # REST API 방식이면 생략 가능
            redirect-uri: https://iotl.store/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG

kis:
  api:
    base-url: ${KIS_CLIENT_URL}
    appkey: ${KIS_CLIENT_ID}
    appsecret: ${KIS_CLIENT_SECRET}
    access-token:

exchange:
  api:
    base-url: ${EXCHAGE_URL}
    base-currency: USD

naver:
  client-id: ${NAVER_NEWS_CLIENT_ID}
  client-secret: ${NAVER_NEWS_CLIENT_SECRET}
  news-url: ${NAVER_API_URL}


server:
  port: 8080
  forward-headers-strategy: native
